/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci.project.server;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
    public static void main(String[] args) throws IOException {
        ServerSocket serverSocket = new ServerSocket(50000);

        while (true) {
            Socket connection = serverSocket.accept();
            System.out.println("Connected");
            new Thread(new ClientHandler(connection)).start();
        }
    }
}
