/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci.project.server;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetSocketAddress;

public class App {
    public static void main(String[] args) throws IOException, Exception {
        DatagramSocket socket = new DatagramSocket(50000);
        while (true) {
            byte[] buf = new byte[1024];
            DatagramPacket packet = new DatagramPacket(buf, buf.length);
            socket.receive(packet);
            
            String received = new String(buf, 0, buf.length).trim();
            InetSocketAddress returnAddress = new InetSocketAddress(packet.getAddress(), packet.getPort());
            Thread clientHandler = new Thread(new ClientHandler(returnAddress, RequestParser.parse(received)));
            clientHandler.start();
        }
    }
}
